### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ykemiche** [pytorch/functorch#1006]
Hi, I have cuda 11.7 on my system and I am trying to install functorch, since the stable version of pytorch for cuda 11.7 is not available [here](https://pytorch.org/get-started/previous-versions/), I just run `pip install functorch` which also installs the compatible version of pytorch.

But when I run my code that uses the GPU, I get the following error :

`RuntimeError: CUDA error: no kernel image is available for execution on the device` 

Is it possible to use functorch in my case?

**Comment by ykemiche** [comment]
I followed [this recommendation](https://discuss.pytorch.org/t/latest-cuda-toolkit-release-11-7-is-it-compatible-with-pytorch/152824/13), I used the supported binary with CUDA 11.3  by runing this command : `pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html --upgrade
`

**Comment by zou3519** [comment]
Ah I see. My hypothesis is that your functorch version and pytorch version are incompatible. If you installed PyTorch via `pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html --upgrade`, then you have a nightly version of PyTorch. 

To install functorch with a nightly version of PyTorch you'd want to install [functorch from source](https://github.com/pytorch/functorch#installing-functorch-from-source): 
```
pip install ninja  # Makes the build go faster
pip install --user "git+https://github.com/pytorch/functorch.git"
```

**Comment by ykemiche** [comment]
That's exactly what I did

**Comment by zou3519** [comment]
Can you please print out the following:
```
import torch
import functorch
print(torch.__version__)
print(torch.version.cuda)
print(functorch.__version__)
```
? Also, are you getting `RuntimeError: CUDA error: no kernel image is available for execution on the device` when you use only PyTorch and no functorch?

For some more context: functorch is CUDA agnostic (it doesn't have any CUDA-specific code), so it's most likely PyTorch that has problems with your CUDA setup.

**Comment by ykemiche** [comment]
That's what I did the first time, I've installed functorch on a venv from source as described on your Readme, by doing : 

`pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html --upgrade
pip install ninja  # Makes the build go faster
pip install --user "git+https://github.com/pytorch/functorch.git"`

I got a wheel building error as you can see on this picture : 

<img width="502" alt="func" src="https://user-images.githubusercontent.com/58120778/186204856-0f7ead02-ae19-4ad4-8443-5a7ec7d6dd9b.PNG">


After that, I started a new venv and directly installed functorch with `pip install functorch` but it seems that the torch version installed by default is incompatible with cuda 11.7.Here is by order, the output of prints :

1.12.1+cu102
10.2
0.2.1

**Comment by zou3519** [comment]
`pip install functorch` installs functorch 0.2.1 which is going to pull in PyTorch 1.12.1 with cu102 support. What you really want is to install PyTorch 1.12.1 with cu113 support. Could you please try the following?
```
pip install torch --extra-index-url https://download.pytorch.org/whl/cu113
pip install functorch
```

**Comment by ykemiche** [comment]
It worked, thanks for your help

**Comment by zou3519** [comment]
Glad to hear. We're working on making installing both pytorch and functorch easier. Please let us know if you have any other feedback.
