### ISSUE TITLE
Running list of OpInfos that don't exist that we'd like

### ISSUE THREAD

**Issue by Chillee** [pytorch/functorch#103]
- [x] argsort @pmeier
- [x] repeat_interleave @pmeier
- [ ] empty_like, ones_like, zeros_like, randn_like, full_like @zou3519 
- [ ] diagflat (https://github.com/pytorch/pytorch/pull/65680)
- [ ] flatten @zou3519 
- [ ] nonzero @zou3519  
- [ ] multinomial
- [ ] allclose
- [ ] unique @zou3519 
- [ ] normal
- [ ] bernoulli
- [ ] fft
- [x] nn.functional.mse_loss
- [ ] nn.functional.l1_loss (https://github.com/pytorch/pytorch/pull/65681)
- [ ] nn.functional.max_pool1d, nn.functional.max_pool3d
- [ ] nn.functional.conv1d, nn.functional.conv3d
- [ ] nn.functional.smooth_l1_loss
- [ ] nn.functional.{selu, glu, hardsigmoid, prelu, celu, silu} (should all be similar)
- [ ] nn.functional.group_norm
- [ ] nn.functional.instance_norm
- [ ] nn.functional.{conv_transpose1d, conv_transpose3d}

**Comment by pmeier** [comment]
I'll take `argsort`.

**Comment by pmeier** [comment]
@Chillee 

> empty_like, ones_like, zeros_like

are creation ops which AFAIK are not yet supported by OpInfo's (cc @mruberry).

**Comment by mruberry** [comment]
> @Chillee
> 
> > empty_like, ones_like, zeros_like
> 
> are creation ops which AFAIK are not yet supported by OpInfo's (cc @mruberry).

This is true in general (because most tensor creation ops are not operations on a tensor) but the *_like ops actually do operate on tensors so they can be OpInfo'd like other ops. In the future we may even want to create a subclass just for them (LikeInfos?).

**Comment by zou3519** [comment]
This issue was tracked elsewhere, and I believe we have all of them now.
