### ISSUE TITLE
Audit CompositeImplicitAutograd ops that do not have a batching rule, add them to BatchRulesDecomposition

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#1087]
This is low hanging fruit: there are a number of CompositeImplicitAutograd ops that do not have a batching rule. We should just add all of them to BatchRulesDecomposition. Should be easy to detect using testing similar to what @srossross did in https://github.com/pytorch/pytorch/pull/89465/files

Here are a couple of things to be careful of:
- If the op has an OpInfo, then we're good (because we have test coverage)
- If there has no test coverage, then ideally we would add an OpInfo. This is because not all CompositeImplicitAutograd operations are ["Composite Compliant"](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/README.md#composite-compliance)
- If there is no test coverage, an alternative to adding an OpInfo is to just read the code and eyeball if it is composite compliant or not. We would prefer having an OpInfo to this option.

**Comment by kshitij12345** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/91367
