### ISSUE TITLE
Add pytorch 1.13.1 compatibility

### ISSUE THREAD

**Issue by scal444** [pytorch/functorch#1095]
When torch 1.13.1 is installed on my machine, and I try to `pip install`  a package with functorch as a dependency, the functorch 1.13.0 package is found and requires downloading of torch 1.13.0. Since functorch >= 1.13 is a dummy package, I'd guess all that's needed is updating pypi

**Comment by zou3519** [comment]
That's a good point. We'll fix this soon.

**Comment by zou3519** [comment]
Should be fixed now

**Comment by scal444** [comment]
Thanks for the quick fix!
