### ISSUE TITLE
Implement batching for nll_loss through decomposition

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#190]
It assumes that the input has size (N, C) and target has size (C,). There is an edge case where the input may be of size (C,) and the target of size ().

**Comment by vfdev-5** [comment]
@zou3519 I was thinking that https://github.com/facebookresearch/functorch/blob/8ab5853a303746f36d93fd46e2af4f93d58b6bb9/functorch/csrc/BatchRulesLoss.cpp#L79-L80
can be optional if `self.dim() == 2` and `target.dim() == 1`.

**Comment by vfdev-5** [comment]
@zou3519 thanks for details. I'll work on that, please assign this issue to me.
