### ISSUE TITLE
{jvp, jacfwd} should accept functions that have pytree inputs and pytree outputs

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#268]
Demonstration from JAX:

- [x] jvp should accept functions that take pytrees as inputs
```
import jax
import jax.numpy as jnp

def f(x):
    a, b = x
    return 2 * a + 3 * b

x = jnp.array([1., 1])
y = jnp.array([1., 1])
t = jnp.array([1., 1])
jax.jvp(f, ((x, y),), ((t, t),))
# (DeviceArray([5., 5.], dtype=float32), DeviceArray([5., 5.], dtype=float32))
```

- [ ] jvp should accept functions that return pytrees
```
import jax
import jax.numpy as jnp

def f(x):
    return {'left': 2 * x, 'right': 3 * x}

x = jnp.array([1., 1])
t = jnp.array([1., 1])
jax.jvp(f, (x,), (t,))
# ({'left': DeviceArray([2., 2.], dtype=float32),
#   'right': DeviceArray([3., 3.], dtype=float32)},
#  {'left': DeviceArray([2., 2.], dtype=float32),
#   'right': DeviceArray([3., 3.], dtype=float32)})
```
It's probably easiest to tackle these separately; but jvp should also accept functions that both accept and return pytrees.

- [x] jacfwd should accept functions that take pytrees as inputs (pre-req is jvp supporting the same)
- [ ] jacfwd should accept functions that return pytrees (pre-req is jvp supporting the same)

**Comment by vfdev-5** [comment]
@zou3519 looks like if we remove 
https://github.com/pytorch/functorch/blob/4eb317aa1b4327116375fd75610c00f4a0620e5f/functorch/_src/eager_transforms.py#L732

and 

https://github.com/pytorch/functorch/blob/4eb317aa1b4327116375fd75610c00f4a0620e5f/functorch/_src/eager_transforms.py#L845

we can have the following:
```python
import torch
import functorch as ft

def g(x):
    return {'left': 2 * x, 'right': 3 * x}

x = torch.tensor([1., 1.5])
t = torch.tensor([2., 2.5])
out = ft.jvp(g, (x,), (t,))
print("-- out dict: ", out)

def f(x, y):
    return {"a": x + y ** 2, "b": x ** 2 + y}

x, y = torch.ones(5), torch.ones(5)
jacobian = ft.jacfwd(f, argnums=1)(x, y)
print("-- out dict jacfwd:", jacobian)
```

**Comment by zou3519** [comment]
@vfdev-5 I put those checks in because I didn't want to think too hard about how to handle pytree outputs. It's possible that everything just works out if we modify the checks :) (and indeed it looks that that might be the case!)

One thing to note is that the check also checks that the only outputs of the function are Tensors. I don't know if JAX allows non-tensor returns from these APIs (e.g. returning an int or a boolean) but we should test that and match their behavior.

**Comment by vfdev-5** [comment]
```python
import jax
import jax.numpy as jnp

def f(x):
    res = (2 * x**2 + 3 * x + 4).sum()
    return [res, int(res), {"res": res}, res > 0]


x = jnp.array([1., 1.5])
t = jnp.array([2., 2.5])
out = jax.jvp(f, (x, ), (t, ))
> ([DeviceArray(22., dtype=float32),
  22,
  {'res': DeviceArray(22., dtype=float32)},
  DeviceArray(True, dtype=bool)],
 [DeviceArray(36.5, dtype=float32),
  array((b'',), dtype=[('float0', 'V')]),
  {'res': DeviceArray(36.5, dtype=float32)},
  array((b'',), dtype=[('float0', 'V')])])
```

Yes, function can return int or boolean and jvp is undefined for them.
