### ISSUE TITLE
Vmap for tensor constructor

### ISSUE THREAD

**Issue by smorad** [pytorch/functorch#279]
Hello, I would like to parallelise the following:

```python
def fn(T, B):
  return [torch.ones(T[b], device=T.device, dtype=torch.long) * b for b in range(B)]
```

Is this possible using `vmap`? The following does not work:

```python
import functorch
def fn(T, B):
  return torch.ones(T, device=T.device, dtype=torch.long) * B

fn = functorch.vmap(fn)

fn(torch.arange(32), torch.arange(32))
```
```
>>> TypeError: ones() received an invalid combination of arguments - got (Tensor, dtype=torch.dtype), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

It seems with `vmap`, `T[i]` cannot be converted to a scalar. When I try to do this manually, I receive another error:
```python
import functorch
def fn(T, B):
  return torch.ones(T.item(), device=T.device, dtype=torch.long) * B

fn = functorch.vmap(fn)

fn(torch.arange(32), torch.arange(32))
```
```
RuntimeError: Batching rule not implemented for aten::item. We could not generate a fallback
```

**Comment by vfdev-5** [comment]
@smorad I think you can not create and return tensors of different size using vmap.

If i understand correctly your code, you would like to create (in "parallel") B tensors of different size ...

**Comment by Chillee** [comment]
So, would you call the original function like `fn(torch.arange(5), 5)` and get as output?
```
[tensor([]), tensor([1]), tensor([2,2]), tensor([3,3, 3])]
```

If so, I don't think this is parallelizable using vmap. Generally with vmap, if you have a function that takes in a tensor of size `[In_0, In_1, ...]` and outputs a tensor of size `[Out_0, Out_1,...]`, then `vmap(f)` will give you a function that takes in a tensor of size `[B, In_0, In_1, ...]` and outputs a tensor of size `[B, Out_0, Out_1, ...]`.

I don't currently see a way to frame your problem like that, but perhaps some more context would help?

**Comment by smorad** [comment]
@Chillee that's correct. I'm working with sparse/variable-size tensors. Things to get a bit more difficult to understand when dealing with indices, which I was hoping `vmap` could help with.

**Comment by Chillee** [comment]
@smorad Unfortunately, I think vmap is of limited use when dealing with sparse/variably-sized tensors. Sometimes if you can represent the variably-sized tensors as a mask then vmap can deal with it, but I'm less hopeful if it also needs to be sparse.

**Comment by smorad** [comment]
Thanks for the info
