### ISSUE TITLE
Set up some linters

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#307]
Like flake8

**Comment by vfdev-5** [comment]
@zou3519 how about using black ?

**Comment by zou3519** [comment]
@vfdev-5 I know nothing about linters, what is the advantage of using black?

@Chillee are you OK with us autoformatting the python pieces of the codebase? This will hide blame information

**Comment by Chillee** [comment]
@zou3519 sounds good to me!

**Comment by vfdev-5** [comment]
@zou3519 basically, flake8 says if code is properly formatted or not. Black does that and also can reformat to be compatible (also using precommit).
Main cons for black adoption are certain conventions they use (and that certain users do not like):
For example, this code 
```python
def my_function(a, b=None, c=None, d=None, too=None, many_args=None, and_more=None, and_more1=None, and_more2=None):
    a = 'a'
    b = [1, 2, 3,]  # trailing comma will make it 1 item per line
    c = {"a": a, "b": b}
    # call function with a lot of args
    another_func(a, b, c, d=d, too=too, many_args=many_args, and_more=and_more, and_more1=and_more1, and_more2=and_more2)
    return 0
```
will be formatted by black into:
```python
def my_function(
    a,
    b=None,
    c=None,
    d=None,
    too=None,
    many_args=None,
    and_more=None,
    and_more1=None,
    and_more2=None,
):
    a = "a"
    b = [
        1,
        2,
        3,
    ]  # trailing comma will make it 1 item per line
    c = {"a": a, "b": b}
    # call function with a lot of args
    another_func(
        a,
        b,
        c,
        d=d,
        too=too,
        many_args=many_args,
        and_more=and_more,
        and_more1=and_more1,
        and_more2=and_more2,
    )
    return 0
```

More info on black: https://github.com/psf/black


In torchvision, it was decided to use `umft`: https://github.com/omnilib/ufmt

**Comment by zou3519** [comment]
Hmm, I see, thanks for the explanation @vfdev-5. My vote is to just use flake8: the motivation I had for having a linter is to eliminate classes of bugs where we use undefined variables or forget to use a variable and to enforce some very basic conventions (e.g. <= 120 char line width so code is still reviewable)

I'm not a big fan of auto-formatting code like in the above example but I can see how it could appeal to others.

**Comment by vfdev-5** [comment]
I agree that we can just setup flake8 first and then figure out other formatter later.
Personally, I like black formatting and trying to use in other open-source projects that I'm maintaining. The code formatting workflow becomes very simple then:
- code without strong thinking about the formatting
- run black
-> code is properly formatted

Certain cons from above message can be avoided if while coding we keep a small awareness of how black works. Otherwise, I agree that auto-formatting can be surprising and may also look ugly...
