### ISSUE TITLE
Batching rules for bitwise integer operations and, or, not, xor, rshift, lshift (both .Tensor and .Scalar)

### ISSUE THREAD

**Issue by trenta3** [pytorch/functorch#312]
Due to the fact that it is currently not possible to vmap over torch.rand, I've ended up coding a PRNG in pytorch to be able to vmap over the returned numbers.
Unfortunately there is a performance drop due to the batching rules not being implemented.
I think these should be easy to add and would speed up my computations quite a bit.

**Comment by vfdev-5** [comment]
There is an experimental support for `torch.randn` and also you can use `torch.rand_like`:
```python
import torch
from functorch import vmap


def func(x):
    y = torch.randn(5)
    return x + torch.rand_like(x) + y * 10.0

t = torch.ones(4, 5)
ret = vmap(func)(t)
print(ret[0])

> script.py:7: UserWarning: Automatically expanding the shape of randn. This means that different elements of vmap will get different random values. If you want different behavior, like using the same random values across vmap, please make a github issue. (Triggered internally at  /ft/functorch/csrc/VmapModeRegistrations.cpp:39.)
  y = torch.randn(5)
tensor([-3.9060, -0.2827,  0.4170,  1.9744, -0.8523])
```

**Comment by Chillee** [comment]
i agree with @vfdev-5 that you can probably get by with using `torch.randn_like` or the more experimental `torch.randn` support.

But I also just added support for all the ops you mentioned (I think?) 

https://github.com/pytorch/functorch/commit/5ae75e20053369f8fb53c92269f0a6f700d6ac7c

**Comment by trenta3** [comment]
Sorry for the late reply, and thanks a lot for adding the operations, the script is working much faster now.
