### ISSUE TITLE
Register things in torch.return_types as PyTrees

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#320]
## Problem

vmap over a function that returns torch.return_types ends up ignoring the torch.return_types:
```
import torch
from functorch import vmap

result = vmap(torch.max, (0, None))(torch.randn(3, 2), 0)
print(result)
# (tensor([-0.7059, -0.0751,  0.9852]), tensor([0, 0, 1]))

torch.max(torch.randn(2), 0)
# torch.return_types.max(
# values=tensor(2.0291),
# indices=tensor(1))
```

`vmap(torch.max, (0, None))(torch.randn(3, 2), 0)` should return something of type torch.return_types.

**Comment by vfdev-5** [comment]
@kshitij12345 can we close this issue as #350 was merged ?

**Comment by kshitij12345** [comment]
Yes. Thanks :)
