### ISSUE TITLE
Fix AOTAutograd with functions where not all outputs require gradients.

### ISSUE THREAD

**Issue by Chillee** [pytorch/functorch#373]

**Comment by hypnopump** [comment]
Indeed. As talked in the discord. forward is ok but backward fails

**Comment by hypnopump** [comment]
How is it going?

**Comment by Chillee** [comment]
Oops, haven't gotten to it yet. i'll do  it tomorrow (hopefully).

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/functorch/commit/f2fae0ed36981b890316f92062e58c35d49e0f15

Lmk if you have any issues!

**Comment by hypnopump** [comment]
Will look into it this week and get back. Looks promising!
