### ISSUE TITLE
test_pythonkey is borked

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#377]
Problem 1: It looks like we deleted make_nnc somewhere?
Problem 2: Deleting the import for make_nnc to make test_pythonkey run results in a segfault on my machine:

cc @Chillee

**Comment by vfdev-5** [comment]
Maybe related to flake8 if `make_ncc` is imported and unused...

**Comment by zou3519** [comment]
Hmm, the repro for the segfault is the following:
```
import torch
import functorch
import torchvision
```

**Comment by zou3519** [comment]
Found the problem: I just have a mismatched torchvision version.

So the last remaining question is, is it intentional that we removed make_nnc?

**Comment by Chillee** [comment]
@zou3519 yeah.

**Comment by zou3519** [comment]
Cool, closing
