### ISSUE TITLE
has_aux flag for jacfwd (and maybe hessian)

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#392]

**Comment by vfdev-5** [comment]
In [JAX](https://jax.readthedocs.io/en/latest/jax.html), `has_aux` flag is present for the following methods:
- grad
- value_and_grad
- jacfwd
- jacrev
- jvp
- vjp

Hessian does not have it. Do you think we would like to have the same API parity ?

**Comment by zou3519** [comment]
Yeah, let's keep API parity. Hessian is implemented in one LOC and users can manually compose jacfwd with jacrev if they want to compute the Hessian and specify auxiliary values.

**Comment by vfdev-5** [comment]
@zou3519 can we merge https://github.com/pytorch/functorch/pull/404 such that it would enable has_aux option for `ft.jvp` ?
