### ISSUE TITLE
Stop running underlying real operation on Tensor in the fallback

### ISSUE THREAD

**Issue by ezyang** [pytorch/functorch#40]
https://github.com/zou3519/functorch/blob/68df44f7cdb72864d5e43674357bca7a57b81220/functorch/csrc/PythonKey.cpp#L125

@Chillee mentioned this to me but I noticed there was no issue for this

**Comment by Chillee** [comment]
Kinda fixed by this :P

https://github.com/pytorch/functorch/pull/349

**Comment by Chillee** [comment]
Added option for this (meta trace)
