### ISSUE TITLE
`vjp` fails for models with buffers

### ISSUE THREAD

**Issue by rejuvyesh** [pytorch/functorch#407]
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import functorch
from functorch import (
    grad, vjp, vmap, jacrev, grad_and_value,
    make_functional, make_functional_with_buffers,
)
from functorch._src.make_functional import (
    functional_init, functional_init_with_buffers,
)

device = torch.device('cpu')

class MLPClassifier(nn.Module):
    def __init__(self, hidden_dim=32, n_classes=2):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.n_classes = n_classes

        self.fc1 = nn.Linear(2, self.hidden_dim)
        self.bn = nn.BatchNorm1d(self.hidden_dim, affine=True)
        self.fc2 = nn.Linear(self.hidden_dim, self.n_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.bn(x)
        x = self.fc2(x)
        x = F.log_softmax(x, -1)
        return x

B = 10
model = MLPClassifier()
fn, weights, buffers = make_functional_with_buffers(model)
inputs = torch.randn(B, 2, device=device)
fn(weights, buffers, inputs)
o, vfn = vjp(fn, weights, buffers, inputs)
vfn(torch.ones_like(o))
```
version:
```
functorch @ git+https://github.com/pytorch/functorch.git@1840714564e206f88ac06bb56694e8112cbe61d2
torch==1.11.0.dev20220121+cpu
```

results in:
```
RuntimeError: only Tensors of floating point dtype can require gradients
```

**Comment by Chillee** [comment]
I don't think this is an issue with `make_functional`, but rather that you're requesting the gradients (with vjp) wrt integer buffers (which batch norm uses).

I can probably write up an example later for this use case.

**Comment by rejuvyesh** [comment]
@Chillee Thanks for the update. I see. Is that the reason there are so many instances of conversion to GroupNorm from BatchNorm in the tests/examples? A lot of `torch.hub` models tend to use `BatchNorm` and would love to know the appropriate syntax for taking `vjp` in such contexts.

**Comment by zou3519** [comment]
This is supposed to be the syntax: https://gist.github.com/zou3519/cbeb69d73f9294e1cd062b8ded8599f5 but it doesn't work because batch_norm performs in-place operations.

We converted many examples of BatchNorm to other types of norms for two main reasons:
1. BatchNorm is tricky to transform over due to in-place operations. It uses in-place operations to update running stats.
2. vmap over BatchNorm is a little weird. In order to do this, one needs to have a full set of buffers instead of a single set of buffers.

@rejuvyesh do you have a little more context around what you're trying to do? Are you just computing vjps or are you interested in other quantities?

**Comment by rejuvyesh** [comment]
Hi @zou3519! Thanks for the context. I have been trying to enable composition of pytorch/jax modules/functions inside julia while ensuring full differentiability. While julia can already call python via PyCall.jl one needs to define the appropriate pullback functions for such pycalls so that it can work with say Zygote.jl AD. `functorch.vjp` makes it extremely easy. The current `torch.hub` example is in https://github.com/rejuvyesh/PyCallChainRules.jl/blob/main/test/test_pytorch_hub.jl. 

It's okay if BatchNorm requires such workaround and I can document as such. But is there a way for me get `vjp` for both params and inputs while ignoring buffers since they are non differentiable? Or the better way would be have to have two sets of `vjp` calls something like:

```python
def push_fn1(weights):
    return fn(weights, buffers, inputs)

def push_fn2(inputs):
    return fn(weights, buffers, inputs)

o, vfn_p = vjp(push_fn1, weights)
vfn_p(torch.ones_like(o))
_, vfn_i = vjp(push_fn1, inputs)
vfn_i(torch.ones_like(o))
```

**Comment by zou3519** [comment]
You can certainly get vjp for both params and inputs. vjp computes vjp-quantities for all inputs passed to the function. So we just need to define a new function that accepts weights and inputs and captures buffers:

```
def push_fn3(weights, inputs)
  return fn(weights, buffers, inputs)

o, vfn = vjp(push_fn1, weights, inputs)
result = vfn(...)
```
