### ISSUE TITLE
Determine how to mitigate the challenge of pytorch/pytorch changes breaking functorch

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#433]
We get broken by pytorch/pytorch on an almost daily basis. Some of these changes are easy to resolve, some are not easy to resolve. This has cost me 10s of hours so far and going forward will cost even more. We should come up with some way to mitigate this.

There are at least two axes for the proposals. On one axis is development velocity for functorch, on the other axis is how much time it takes for us to get notified of a change in pytorch/pytorch that is problematic. These generally get traded off in the proposals.

Some proposals that we've heard so far:
- Follow what pytorch/xla did. That is, have a test in pytorch/pytorch that builds functorch main and signals if there's a problem. The tradeoff here is that functorch main must now be green most of the time (e.g. no more committing directly to main) and we need our CI to run off of pytorch main, not the pytorch nightlies.
- The pytorch/xla idea, except, the test always reports green but emails someone if there is a problem.
- Just merge functorch into pytorch/pytorch. This gives us the fastest signal to a problematic change (in fact, the problematic change won't get merged if they break a functorch test), but it trades off our development velocity completely.
- put functorch as a submodule on pytorch/pytorch, package the two libraries together

**Comment by samdow** [comment]
Nightly testing is set up [here](https://app.circleci.com/pipelines/github/pytorch/functorch/1965/workflows/84067261-47b1-428c-bbf9-72f66e2dafc0). First test ran against the previous day's nightly so tried to set it to run later (we'll see tomorrow)

Also going to add a weekly test to build + run on pytorch/master
May also try to have nightly run vmapvjpvjp tests (need to figure out some timeout issues)

**Comment by zou3519** [comment]
Done; we moved functorch into PyTorch.
