### ISSUE TITLE
vmap should support out_dims=None

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#439]
Currently, all the outputs of vmap must be Tensors. We can relax this constraint by letting the user specify `None` for an out_dim (which means, return the object as-is). 

```py
def f(x):
  return 1

x = torch.randn(3)
result = vmap(f, out_dims=(None,))(x)
assert result == 1
```

There are some interesting cases (that we should look to JAX to for what the semantics should be):
- what happens if we specify out_dims=None on a Tensor return, but the Tensor is being vmapped over?

**Comment by Chillee** [comment]
What does this mean 🤔

**Comment by zou3519** [comment]
- This allows us to return non-Tensors (e.g. strings) from vmap (right now vmap assumes that all outputs are tensors).
- If a returned tensor was not vmapped over at all (e.g. it is still a Tensor and not a BatchedTensor) then this allows the user to return the Tensor in its unexpanded form. This is useful for implementing has_aux = True for jacfwd (cc @vfdev-5).

**Comment by vfdev-5** [comment]
In terms of API, we would like to have the following ?

1) `out_dims=None`
```python
def foo(x):
    return "abc"

assert vmap(foo, out_dims=None)(torch.rand(4, 3)) == "abc"
```

2) `out_dims=(0, None)`
```python
def foo(x):
    return x.sum, "abc"

x = torch.rand(4, 3)
assert vmap(foo, out_dims=(0, None))(x) == (x.sum(dim=1), "abc")
```

**Comment by zou3519** [comment]
This is what I'm thinking -- is this how both of the above work in JAX?

**Comment by vfdev-5** [comment]
Yes, JAX does something like that (however, str is not supported)
```python
import jax
import jax.numpy as jnp

def foo(x):
    return 12

x = jnp.ones([4, 3])
jax.vmap(foo, out_axes=None)(x)
> 12
```
and
```python
import jax
import jax.numpy as jnp

def foo(x):
    return x.sum(), 12

x = jnp.ones([4, 3])
jax.vmap(foo, out_axes=(0, None))(x)
> (DeviceArray([3., 3., 3., 3.], dtype=float32), 12)
```

**Comment by samdow** [comment]
From a quick check, JAX doesn't allow string returns:
```
TypeError: Value 'abc' with type <class 'str'> is not a valid JAX type

The above exception was the direct cause of the following exception:

UnfilteredStackTrace                      Traceback (most recent call last)
UnfilteredStackTrace: TypeError: Output from batched function 'abc' with type <class 'str'> is not a valid JAX type
```

However, you can have `out_dims=None` for a tensor return and then
```
def foo(dummy):
  return jnp.ones([3])
```
returns a tensor of size [3]

**Comment by kshitij12345** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/91644
