### ISSUE TITLE
Version selector for the docs

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#451]
It would be nice if we had a docs page for nightly functorch and a docs page for the release/0.1 branch. In the absence of this then we will have to just use the release/0.1 branch, but this risks users not finding updated features we put out.

**Comment by zou3519** [comment]
Prior art:
- @vfdev-5  mentioned that ignite uses a fork of sphinx-versioning (yikes!) https://github.com/pytorch-ignite/sphinxcontrib-versioning
- pytorch/pytorch just copy-pastes things and has a manual version selector...

**Comment by vfdev-5** [comment]
We can also replicate what vision does: https://pytorch.org/vision/stable/index.html

**Comment by zou3519** [comment]
What vision does sounds like the easiest thing to do here

**Comment by zou3519** [comment]
exists
