### ISSUE TITLE
functorch build+test time went from 50m to 20m in the last two months

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#454]
This is normally a cause for celebration, but AFAIK we did not do anything to reduce the build+test time. This warrants an investigation -- we should check that we're still running all of our tests.

See https://app.circleci.com/insights/github/pytorch/functorch/workflows/unittest/overview?branch=main for details

![image](https://user-images.githubusercontent.com/5652049/152566044-e80b365d-ebc7-439d-b18e-3bed9c6f3c29.png)

**Comment by zou3519** [comment]
One possibility is that we landed some batching rules between Jan 6th and Jan 8th and that decreased testing time.

**Comment by samdow** [comment]
It looks like `test_ops.py` went from "Ran 16445 tests in 1586.865s" to "Ran 4346 tests in 70.133s", stopping after `test_decomposition_linalg_det_singular_cuda_float64`. Really unclear why that happened since the surrounding diffs don't change anything in that file
