### ISSUE TITLE
Decomposition tests failing on CUDA

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#460]
https://app.circleci.com/pipelines/github/pytorch/functorch/1323/workflows/e53da1f4-8571-415f-bc08-f7a6e3dbd2f2/jobs/7934
test_decomposition_log_softmax_cuda_bfloat16
test_decomposition_nn_functional_softmin_cuda_bfloat16

Going to skip for now to get CI green.

@Chillee do we need to adjust the tolerance?

**Comment by Chillee** [comment]
Sigh, maybe.

Not sure if there's a better way to test tolerance on these ops...

**Comment by Chillee** [comment]
Fixed already
