### ISSUE TITLE
Is the accumulation of PythonTensor objects inevitable?

### ISSUE THREAD

**Issue by hyunwoongko** [pytorch/functorch#480]
Currently, DynamicShapeHasher does not work correctly, so if a new shape is input, a new compilation is required. However, every time I compile, it seems that [`PythonTensor`](https://github.com/pytorch/functorch/blob/main/functorch/_src/python_key.py#L58) objects keep piling up somewhere. Can I remove this from memory when the compilation is done?

**Comment by Chillee** [comment]
Could you give an example?

**Comment by hyunwoongko** [comment]
'll check a little more and make it clear.
