### ISSUE TITLE
Delete TestOpAuthoring

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#482]
Running pytest in parallel produces the following:
![image](https://user-images.githubusercontent.com/5652049/153669468-fb1eecc2-2b1f-436a-a7df-4e99b4319002.png)

cc @Chillee @anijain2305 not sure how concerning this is

**Comment by zou3519** [comment]
I've been seeing these tests in single-threaded pytest so I'm more concerned now, maybe DynamicLayer is not cleaning up the include/exclude set

**Comment by Chillee** [comment]
🤔 I guess I still don't understand how this could even happen. 

Wait, also `test_operator_authoring` is actually not that relevant to us. It's the old "Operator Authoring" prototype Bert checked in a long time ago.

**Comment by zou3519** [comment]
Oh, should we delete it?

**Comment by Chillee** [comment]
We could, yeah (unless you want to look into why these strange errors are being thrown...).

But these tests have nothing to do with AOTAutograd.

**Comment by zou3519** [comment]
It was a bug, we fixed it. Remaining action item is: "Delete test_operator_authoring", we don't need it anymore
