### ISSUE TITLE
Easy way to set per-op per-OpInfo per-dtype test tolerances?

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#483]
Rationale: https://github.com/pytorch/functorch/issues/468

**Comment by samdow** [comment]
For whoever does this, it would similarly be good to remove all the infra having to happen in `test_decompositions` and replace it with the general solution ([ref](https://github.com/pytorch/functorch/blob/main/test/test_ops.py#L1035-L1042))

**Comment by zou3519** [comment]
I implemented this
