### ISSUE TITLE
ModuleNotFoundError: No module named 'functorch' 

### ISSUE THREAD

**Issue by Coderx7** [pytorch/functorch#490]
The colab link for the [functormain ](https://github.com/pytorch/functorch#installing-functorch-main) ([colab link](https://colab.research.google.com/drive/1CrLkqIrydBYP_svnF89UUO-aQEqNPE8x?usp=sharing)) fails at running the provided example stating : 
`ModuleNotFoundError: No module named 'functorch' `

Whats wrong here? How should we install the latest version then?

**Comment by Chillee** [comment]
You need to restart your runtime after completing the installation instructions.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6355099/153911546-596b32b4-984e-45f8-8a62-0ecdfaced315.png">

**Comment by Coderx7** [comment]
@Chillee Thanks a lot! completely missed that!
