### ISSUE TITLE
CircleCI deprecated image migration

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/functorch#496]
Message from Circle CI:

> Hello,
> We are deprecating Ubuntu 16.04-based machine images on CircleCI in preparation for an EOL on Tuesday, May 31, 2022 to ensure your builds remain secure. For a detailed overview of how this will affect your workflow, [read the blog article here](https://go.circleci.com/NDg1LVpNSC02MjYAAAGCndaN_cRYYwX33ur-wAFnCU8YFKlpvjKxlwwakuzkoaSAgJj2ITxfA-VpHvPCDMRnTEbY_fU=).
> We will also be conducting temporary brownouts on Tuesday, March 29, 2022, and again on Tuesday, April 26, 2022 during which these images will be unavailable.
> We are contacting you because one or more of your projects has a job that uses an Ubuntu 16.04-based image.
> The project(s) using an image based on Ubuntu 16.04 are:
[functorch] [functorch] [functorch] [functorch][functorch] [functorch]...
> If you have specified an Ubuntu 16.04-based image please see our [migration guide](https://go.circleci.com/NDg1LVpNSC02MjYAAAGCndaN_RXbgQlzeiyJpGdSaN90uyAuFWIffOxAZ4o508pd4n9Y56q62u_dxUWy-IRUiGiY314=) to upgrade to a newer version of Ubuntu image in order to avoid any service disruption during the brownout & subsequent EOL.

- https://circleci.com/docs/2.0/images/linux-vm/16.04-to-20.04-migration/

**Comment by zou3519** [comment]
Actionable to figure out how PyTorch is dealing with this and copy them

**Comment by vfdev-5** [comment]
PyTorch is on GHA now, vision is still on CircleCI

**Comment by samdow** [comment]
Still seeing [some PyTorch tests using CircleCI](https://github.com/pytorch/pytorch/blob/master/.circleci/config.yml#L569). Looks like they upgraded to 20.04. We can probably use that one unless we want to upgrade further

**Comment by vfdev-5** [comment]
That's true that there are some tests running on circleci. Yes, we can upgrade to 20.04.
