### ISSUE TITLE
Hook up functorch transforms to the autograd.functional benchmarks

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#497]
autograd.functional has benchmarks: https://github.com/pytorch/pytorch/blob/master/benchmarks/functional_autograd_benchmark/utils.py

We should add an option to run them using functorch. It'll probably look something like "if can import functorch, then run them, otherwise, just do the usual thing of autograd.functional"

Motivation
- To get a clearer sense of what functorch perf really looks like when compared with autograd.functional. We have anecdata of order-of-magnitude speedups on various models.

cc @albanD @soulitzer if you folks have thoughts on if the benchmarks should go there or elsewhere

**Comment by vfdev-5** [comment]
List of issues discovered when running benchmark:
- #632
- #629
- #628
- #626

**Comment by vfdev-5** [comment]
@zou3519 as https://github.com/pytorch/pytorch/pull/75689 was merged can we close this issue or there is still something else to be done ?

**Comment by zou3519** [comment]
Nope, that looks good to me
