### ISSUE TITLE
Set up main docs build

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#500]
Set up a docs build in the CI. Upon changes to the main branch (or maybe on a nightly basis?) we should push to https://pytorch.org/functorch/main/ .

Motivation:
- Automation: Saves me/us some hours of remembering how to set up the docs build and needing to rebuild the docs periodically :)
- We can totally reuse this for the documentation for the release branch as well

**Comment by vfdev-5** [comment]
Sounds good, i'll rename it and try to figure out a GHA how to copy and commit to gh-pages branch.

> Finally, do you have suggestions for how to not accumulate a lot of history?

maybe something like `git commit --amend && git push -f`

**Comment by zou3519** [comment]
How bad is accumulating a lot of history? I know that checking out pytorch.github.io is ridiculously slow, but if it's not too bad we can start out with manually squashing the history of that branch every once in a while. It's useful to be able to roll back changes if something goes wrong

**Comment by vfdev-5** [comment]
> How bad is accumulating a lot of history? 

I can't tell in general, I had an experience with a repository where we didn't for some time squashed the history and repository grew to ~700MB from ~50MB. My lesson learnt -> no history storage.

> It's useful to be able to roll back changes if something goes wrong

Well, sources are still in `main` branch. If we have to roll back, we can rebuild manually and push built docs to gh-pages if needed...

**Comment by zou3519** [comment]
> Well, sources are still in main branch. If we have to roll back, we can rebuild manually and push built docs to gh-pages if needed...

Seems reasonable
