### ISSUE TITLE
Add Batching Rule for convolution_double_backwards

### ISSUE THREAD

**Issue by xmser** [pytorch/functorch#516]
Hello and thank you for the great project:
I try to use funtorch to calculate the derivative of the loss function with respect to the weight and the second derivative with respect to the weight ,  the second order partial derivative of the loss function with respect to the sample, and the second order partial derivative of the loss with respect to the weight and the sample in the deep learning model. Just like the picture~
![partial](https://user-images.githubusercontent.com/50072084/154632302-73c9bfd3-1050-43fa-a627-5ad2c21ca913.PNG)

I tried this with the MNIST dataset, and there are some problems, my basic idea is to use the nesting of jacrev to implement the  partilal hessian.
`

    # test on sample, batch_size=1
    pass_loader = DataLoader(train_data, batch_size=1, shuffle=False)

    func_model, params = make_functional(model)

    def compute_loss(params, image, label):
        output = func_model(params, image)
        return criterion(output, label)   #ceriteration:   torch.nn.CrossEntropyLoss

    partial_xx = jacrev(jacrev(compute_loss, argnums=1), argnums=1)

    for index, (image, label) in enumerate(pass_loader):
        image = image.to(device)
        image.requires_grad = True
        label = label.to(device)

        jacbian_index = partial_xx(params, image, label)
        print(jacbian_index.shape)
        if index == 0:
            break
`
when I try to calculate the partial hessain for respect to sample and sample, I receive the follow warning.:

[W BatchedFallback.cpp:108] Warning: There is a performance drop because we have not yet implemented the batching rule for aten::cudnn_convolution_backward. Please file us an issue on GitHub so that we can prioritize its implementation. (function warnFallback)
![23](https://user-images.githubusercontent.com/50072084/154635778-5b2b57c4-bcf1-4e6d-9c29-d8c39520a61e.png)

when I try to calculate the partial hessian for parameters, the follow error:

Traceback (most recent call last):
  File "testNNmodel.py", line 122, in <module>
    jacbian_index = partial_xx(params, image, label)
  File "/home/jing/.local/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 358, in wrapper_fn
    output, vjp_fn = vjp(f_wrapper, *primals)
  File "/home/jing/.local/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 229, in vjp
    primals_out = f(*diff_primals)
  File "/home/jing/.local/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 407, in f_wrapper
    replaced_args = _replace_args(args, wrapper_args, argnums)
  File "/home/jing/.local/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 380, in _replace_args
    raise RuntimeError(f'new_args should be of size 1, was of size {len(new_args)}')
RuntimeError: new_args should be of size 1, was of size 10

The following is my total code,  my basic idea is pretrain a model and then caluculate the partial hessian respect to parameters and sample.

`    

    import torch
    import torch.nn as nn
    from functorch import jacrev, vmap, make_functional, grad
    from utils import total_params
    import torchvision
    from torchvision.datasets import MNIST
    from torch.utils.data import DataLoader
  
     # my model struct 
    class CNN(nn.Module):
        def __init__(self):
            super(CNN, self).__init__()
            
            self.layer = nn.Sequential(
                nn.Conv2d(1,4,5), # 4*24*24
                nn.ReLU(),
                nn.Conv2d(4,8,5), # 8*20*20
                nn.ReLU(),
                nn.MaxPool2d(2,2), # 8*10*10
                nn.Conv2d(8,16,5), # 16*6*6
                nn.ReLU(),
                nn.MaxPool2d(2,2) #16*3*3
            )
            
            self.fc_layer = nn.Sequential(
                nn.Linear(16*3*3,100),
                nn.ReLU(),
                nn.Linear(100,10)
            )       
            
        def forward(self,x):
            out = self.layer(x)
            out = out.view(-1,16*3*3)
            out = self.fc_layer(out)

            return out

    device = 'cuda'
    model = CNN().to(device)
    print(total_params(model))

    dataroot = '../data'
    transformer = torchvision.transforms.Compose([torchvision.transforms.ToTensor(),])

    train_data = MNIST(dataroot, train=True, transform=transformer, download=True)
    test_data = MNIST(dataroot, train=False, transform=transformer, download=True)

    batch_size = 128
    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=False, num_workers=2)

    optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

    criterion = torch.nn.CrossEntropyLoss()

    for epoch in range(5):
        print('epoch : {}'.format(epoch+1))
        for image,  label in train_loader:

            image = image.to(device)
            label = label.to(device)

            output = model(image)
            loss = criterion(output, label)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    pass_loader = DataLoader(train_data, batch_size=1, shuffle=False)

    func_model, params = make_functional(model)

    def compute_loss(params, image, label):
        output = func_model(params, image)
        return criterion(output, label)

    def re_shape(mm):
        return torch.cat([g.view(-1) for g in mm])

    def grad_w(params, image, label):
        grad_w = grad(compute_loss, argnums=1)(params, image, label)
        return torch.cat([g.view(-1) for g in grad_w])
        # return grad_x
    jacbian = jacrev(grad_w, argnums=1)

    partial_xx = jacrev(jacrev(compute_loss, argnums=1), argnums=1)

    for index, (image, label) in enumerate(pass_loader):
        image = image.to(device)
        image.requires_grad = True
        label = label.to(device)
        #grad_x = grad(compute_loss)(params, image, label)
        #grad_x = torch.cat([g.view(-1) for g in grad_x])
        jacbian_index = partial_xx(params, image, label)
        print(jacbian_index.shape)
        if index == 10:
            break
`

**Comment by xmser** [comment]
Hi@samdow, thank you very much ! At the beginning, I use the way 'Installing functorch preview with PyTorch 1.10' to do above problem. After your advice I change to main functorch, it could solve my problem.  In addition, the compiler give me a warning  :

lib/python3.8/site-packages/torch/autograd/__init__.py:275: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::_convolution_double_backward. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at  /tmp/pip-req-build-556l0iei/functorch/csrc/BatchedFallback.cpp:84.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

May I ask you if this is just a performance degradation and will not cause errors in the calculation results 。

**Comment by Chillee** [comment]
@xmser It's just a performance degradation, although it *might* be a significant performance degradation. We'll look into it :)

**Comment by samdow** [comment]
For clarity, it's a performance degradation from the optimal but it shouldn't be a performance degradation between 1.10 and main (it's really hard to see but in the original warning messages, `aten::_convolution_double_backward` was mentioned as well as `aten::_convolution_backward`. Because this is something you're relying on, like Horace said, we'll prioritize looking into it

For my organization, would you mind either changing the name of this issue or filing a new issue on asking for a batching rule for `aten::_convolution_double_backward`? We can also help with either of these, it's just nice to remember who originally asked for it 😄

**Comment by Chillee** [comment]
We added it in this PR: https://github.com/pytorch/functorch/pull/557

Let us know whether it works!

**Comment by zou3519** [comment]
Closing as fixed, but please do let us know if it worked for you, @xmser!

**Comment by xmser** [comment]
First of all thank you for your excellent work. It did the job well on a small model I built. However, for more complex models like resnet20, VGG16 (using cifar10 dataset), I want to get the following second-order information $\frac{\partial^2 loss}{\partial sample \partial sample}$ and $\frac{\partial^2 loss}{\partial sample \partial params}$. For the $\frac{\partial^2 loss}{\partial sample \partial params}$, because the params itself is relatively large (its storage is unimaginable), I want to ask whether it is possible to adopt a layer-wise strategy to obtain second-order information for a specific layer，for example $\frac{\partial^2 loss}{\partial sample \partial params[layer_name]}$.Another trickier problem is that I can't calculate $\frac{\partial^2 loss}{\partial sample \partial sample}$, it works perfectly on small models. So is the scale of the model itself limiting this calculation, or is there some other problem in my code. My code is as follows, I am using 3090, 24G. pytorch version 1.11. Thanks again~

`

    def test_jacobian(self, ):

        def compute_loss(params, image, label):
            preds = self.func_model(params, image)
            return self.criterion(preds, label)

        jacobian_sample = jacrev(compute_loss, argnums=1)
        jacobian_sample_sample = jacrev(jacobian_sample, argnums=1)

        loader = self.dataer.get_loader(isTrain=True, batch_size=1)

        for image, label in loader:
            image = image.to(self.device)
            label = label.to(self.device)
            image.requires_grad = True
            partial_xx = jacobian_sample_sample(self.params, image, label)

            print(partial_xx.sum())
            break

    if __name__ == "__main__":
         os.environ['CUDA_VISIBLE_DEVICES'] = '2'
         dataer = Dataer(dataset_name='Cifar10')
         neter = Neter(dataer=dataer, args=None) #resnet20 no Bn
         blocker = BasicBlock(net=neter.net, dataer=dataer, 
        criterion=neter.criterion, device=neter.device)
        # blocker.get_sample_grads()
        blocker.test_jacobian()


`
![issue](https://user-images.githubusercontent.com/50072084/171548352-a3e7bb75-c2d3-4633-82bb-e65f09d0d205.PNG)
