### ISSUE TITLE
pytorch-sphinx-theme renders weirdly with our notebook tutorials

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#524]
1. The colab button is huge!
2. there's so much extra space in the code block.

cc @vfdev-5 since you seem to be good with HTML/CSS. I tried to fix this for a couple of minutes, realized my lack of web dev knowledge, and then gave up

![image](https://user-images.githubusercontent.com/5652049/154770993-51d3c621-1683-49fc-a363-9d895f49ab9f.png)

**Comment by zou3519** [comment]
The "nuclear" option is to go back to our old readthedocs theme lol (e.g. http://pytorch.org/maskedtensor/main/notebooks/nan_grad.html)

**Comment by vfdev-5** [comment]
This way user wont miss to open the tutorial in the colab :)

readthedocs or pytorch-theme I think it is up to you to decide if you can easily tweak it later...
I'm not that good at HTML/CSS, just imitating what was done for ignite :) 
I can try to fix the size and see.

**Comment by vfdev-5** [comment]
@zou3519 we can either fix it in CSS globally as pytorch sphinx theme defines for articles:
```css
article.pytorch-article img {
  width: 100%;
}
```
So, we can do 
```css
article.pytorch-article img {
  width: auto;
}
```
This means that all images wont be sized to width 100%.

2 solution we can just override the style for "Open in Colab" badges:
```
    "<a href=\"https://colab.research.google.com/github/pytorch/functorch/blob/main/notebooks/colab/jacobians_hessians_colab.ipynb\">\n",
    "  <img style=\"width: auto\"src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/>\n",
    "</a>\n",
```

**Comment by vfdev-5** [comment]
@zou3519 I can check. I remember we had that as well previously but unfortunately I do not quite remember what was the issue...
