### ISSUE TITLE
Docs version picker for main gives broken link

### ISSUE THREAD

**Issue by samdow** [pytorch/functorch#542]
In the doc version picker (which is excellent, btw), if you click the first one, it goes to a broken link of pytorch.org/functorch/main
If you click the second one, it goes to a broken link of pytorch.org/functorch/0.1.0

<img width="728" alt="Screen Shot 2022-02-25 at 5 45 22 PM" src="https://user-images.githubusercontent.com/17888388/155813281-4f1751c6-bc73-44c6-be9d-e6d07e4cd729.png">

**Comment by vfdev-5** [comment]
It is expected that v0.1.0 is broken as we do not have any 0.1.0 folder for this : https://github.com/pytorch/functorch/tree/gh-pages

**Comment by samdow** [comment]
Closing for working main/nightly link and since 0.1 not working is expected
