### ISSUE TITLE
attribute lookup is not defined on builtin

### ISSUE THREAD

**Issue by soodoshll** [pytorch/functorch#569]
Hi! I'm playing with this fun project following the [tutorial](https://pytorch.org/functorch/nightly/notebooks/aot_autograd_optimizations.html#operator-fusion), but it raises an error:

```
RuntimeError: 
attribute lookup is not defined on builtin:
  File "<eval_with_key>.4", line 8
    add_1 = torch.ops.aten.add(add, primals_3);  add = primals_3 = None
    add_2 = torch.ops.aten.add(add_1, primals_4);  add_1 = primals_4 = None
    cos_default = torch.ops.aten.cos.default(add_2)
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    cos_default_1 = torch.ops.aten.cos.default(cos_default)
    return [cos_default_1, add_2, cos_default]
```

My environment:

* torch: 1.12.0a0+git076619d
* functorch: 0.2.0a0+4b24eef

**Comment by zou3519** [comment]
cc @Chillee @anijain2305

**Comment by Chillee** [comment]
@soodoshll There was a recent change (https://github.com/pytorch/pytorch/pull/72673) that changed these things - I'll have a fix up soon.

**Comment by Chillee** [comment]
@soodoshll Should be fixed by this (https://github.com/pytorch/functorch/commit/b83273b25213f556f05a065163163ba531e24750) - let me know if it works!

**Comment by soodoshll** [comment]
@Chillee It works! Thanks :)
