### ISSUE TITLE
Possible bug (?) with vmap hessian

### ISSUE THREAD

**Issue by Parskatt** [pytorch/functorch#597]
## Code to reproduce
```python
import torch
from functorch import grad, hessian, vmap, jacrev, jacfwd

b = 8
n = 100
d = 2
x1 = torch.randn(b,n,d)
x2 = x1
A = 0.1*torch.randn(b,d,d)

def l(A,x1,x2):
    x2_hat = (A@(x1.T)).T
    res = x2-x2_hat
    res_sqr = res**2
    return res_sqr.sum()

hess1=vmap(jacrev(jacrev(l)))(A,x1,x2)
hess2=vmap(hessian(l))(A,x1,x2)
```
Gives:
> RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 1

For vmap hessian, but not for double backwards jacobian.

## Environment
Using pytorch==1.11 and functorch==0.1.0

**Comment by Chillee** [comment]
Specifically, this actually looks like a problem with `jacfwd`. You can see that the hessian transform is a trivial composition of `jacfwd` and `jacrev`: https://github.com/pytorch/functorch/blob/main/functorch/_src/eager_transforms.py#L997

**Comment by zou3519** [comment]
And here's a minimal repro:
```
import torch
import functorch
from functorch import vmap


x = torch.randn(8, 4, 3, 2)
y = torch.randn(8, 3, 2)

result = vmap(vmap(torch.ops.aten._new_zeros_with_same_feature_meta, in_dims=(0, None)))(x, y)
assert result.shape == x.shape, result.shape
```

**Comment by zou3519** [comment]
https://github.com/pytorch/functorch/pull/603 will hopefully fix this

**Comment by zou3519** [comment]
@Parskatt, https://github.com/pytorch/functorch/pull/603 fixed this. The fix will be in our next minor release (to come in < 1 mo).

To use it earlier, here are some options:

(1) install the release branch from source (works with PyTorch 1.11)
```
# Makes the build go faster
pip install ninja
# Takes around 5-6 minutes to install
pip install --user "git+https://github.com/pytorch/functorch.git@release/0.1"
```

(2) Install functorch development branch from source (requires a PyTorch nightly binary)
https://github.com/pytorch/functorch#installing-functorch-from-source

Please let us know if your problem still persists and if there's anything else we can help out with!

**Comment by Parskatt** [comment]
@zou3519 great, thanks!
