### ISSUE TITLE
Infra upgrades

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#601]
First two are the most important
- [ ] Set up Python 3.10 job (functorch supports Python 3.7  to 3.10
- [ ] Set up test jobs for our binary builds (i.e. the jobs should test the built binaries)
- [x] Figure out what to do about the "ubuntu 16.04 image deprecation"
- [ ] think about if we need CUDA 11.3 jobs (or can migrate 11.1 -> 11.3, or something)
- [ ] think about if we can delete our .circleci config for gha

**Comment by vfdev-5** [comment]
https://github.com/pytorch/functorch/pull/599 related to fix Ubuntu 16.04 image depreciation.

**Comment by zou3519** [comment]
Completed
