### ISSUE TITLE
[doc] wrong comment

### ISSUE THREAD

**Issue by SsnL** [pytorch/functorch#604]
It should not raise an error based on the description.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/5674597/158652481-9925d640-e3a8-4782-9004-b63d54c945c0.png">

**Comment by zou3519** [comment]
Agreed. Thanks for reporting, @SsnL

**Comment by SsnL** [comment]
One more comment: I think the use of `sufficient memory` can be a bit confusing. Here it really means whether there is a 1-to-1 mapping, a property of the input tensors and the op, regardless of the hardware memory constraints. But `sufficient memory` may lead people thinking that they don't have enough CPU/GPU memory (and having more memory would solve the issue). @zou3519

**Comment by zou3519** [comment]
Fair enough, thanks for that feedback! Please let us know if if you have suggestions for more things :)
