### ISSUE TITLE
[Release Tracker] functorch 0.1.1 minor release 

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#650]
The tentative deadline for commits is 4/8. We plan to release sometime the week of 4/12. The dates are flexible but we can also release more dot releases (e.g. 0.1.2)

If there is an issue you'd like to fix before the release, please tag it with the 0.1.1 milestone so we can track it.

In general, if the commit you wish to include looks too risky (e.g., refactors DynamicLayer :P), we might reject it or request more testing.

## Logistics

If there is a commit you want to get into the release, please:
1. land the commit into the main branch
2. Create (but do not merge) a PR against the release branch (`release/0.1`)
3. Make a request below with the link to your PR against the release branch
4. Make sure that tests pass.

@zou3519 (or whoever's name is here) will merge the PRs into the release branch when tests pass. Please don't merge the PR yourself or it might get too hectic.

**Comment by samdow** [comment]
#649

**Comment by samdow** [comment]
- [ ] #682 
- [ ] #684

**Comment by zou3519** [comment]
We've released: https://github.com/pytorch/functorch/releases/tag/v0.1.1
