### ISSUE TITLE
vmap, jacrev should have an option to vectorize "chunks" instead of the entire batch at a time

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#680]
We've received issues recently around OOMs (https://github.com/pytorch/functorch/issues/673, https://github.com/pytorch/functorch/issues/636). These require more investigation, but one potential simple fix is to give e.g. vmap a flag to break up the computation into chunks so that we end up using less peak memory.

For example, `vmap(torch.sin, chunks=4)(inputs)` would do something like:
```
inputs.chunk(4)
torch.stack([vmap(f, chunks=1)(input) for input in inputs])
```

**Comment by vfdev-5** [comment]
I'll give a try to vmap with chunks

**Comment by zou3519** [comment]
So, I think there are some open API questions.

In the current proposal (from @vfdev-5), vmap has a chunks argument and:
- we run vmap on each chunk
- then, we move each chunk to CPU
- then, we torch.stack each chunk
- finally, we move the stacked tensor to the original device
This is to avoid the situation where we're using a lot of memory.

Now, my question is: if we do `vmap(vmap(f,chunks=2), chunks=2)(x)`, then do we do the "stack on CPU" thing twice?

Next, is it useful to control chunks at a per-vmap level? One alternative UX is some global flag that changes all vmaps to use some number of chunks.

**Comment by zou3519** [comment]
Updating the issue. The current state of things is: vfdev-5 implemented functorch.experimental.chunk_vmap. We put it into the experimental namespace because we were unsure of the API and if folks would use it.

It's time to bring the functionality into the main APIs. In particular, we want to give a `chunks` argument to functorch.vmap and functorch.jacrev (it doesn't quite make sense to give it to functorch.jacfwd or functorch.hessian). There is some design decision to be made here:
- what do we name the flag?
- what is the behavior when things aren't evenly divisible?

we should look at whatever API we recommend people to use for splitting Tensors and be consistent with it (there is torch.chunk, torch.split, torch.tensor_split, ...)

For functorch.jacrev: I'm concerned the way we compute jacobians is inefficient for multiple outputs and we may also need to re-think how we compute jacobians before we add the `chunks` argument. In particular, if we have:
```
def f(x):
  return x ** 2, x.sum()

x = torch.randn(3)
jacrev(f)(x)
```
then we end up constructing a 4x4 identity matrix, splitting into 4x3 (a) and 4x1 (b) and then doing `vmap(vjp_fn)(a, b)`. There is some alternative strategy where we compute the jacobian for output0 first and then the jacobian for output1 and finally concatenate them. This could be faster (and use less memory!).

**Comment by kshitij12345** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/91157 and https://github.com/pytorch/pytorch/pull/89376
