### ISSUE TITLE
NotImplementedError: Trying to use forward AD with rsub that does not support it

### ISSUE THREAD

**Issue by bchen0** [pytorch/functorch#719]
Hi all,

When trying to calculate the Hessian of a function, I've run into the error "NotImplementedError: Trying to use forward AD with <function> that does not support it", such as rsub. I had two questions:

1) Is there a list somewhere of functions that are not yet supported?
2) Is there a way to identify where in my code this is breaking? For instance, stepping into a debugger doesn't seem to allow me to pinpoint where exactly I am using rsub. This would be useful so that I could consider alternatives.

Thanks

**Comment by Chillee** [comment]
It seems like rsub is supported in PyTorch nightly. See https://github.com/pytorch/pytorch/issues/71117

> Is there a way to identify where in my code this is breaking? For instance, stepping into a debugger doesn't seem to allow me to pinpoint where exactly I am using rsub.

Could you post the error? If it's in your user-code I think it should be clear-ish. But if it's being called internally in PyTorch, it'll be more difficult.

**Comment by bchen0** [comment]
Switching to the nightly version seems to have worked. Thanks!
