### ISSUE TITLE
Add a linearize like jax.linearize

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#724]
`jvp(f, x, tangents)` computes both f(x) and the Jacobian-vector product.

The goal of `linearize(f)` is to return a function that can compute forward-mode AD multiple times without re-evaluating f(x).

**Comment by TJHeeringa** [comment]
Is there a workaround until a function like this has been properly implemented?

**Comment by zou3519** [comment]
A workaround is to use `jvp` -- jvp will re-evaluate the function you pass to it every time, so the performance won't be as good.

**Comment by kshitij12345** [comment]
Added in https://github.com/pytorch/pytorch/pull/94173
