### ISSUE TITLE
getitem bug

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#745]
```
from functorch import vmap
import torch
def f(x):
    return torch.ones(4)[x]

y = torch.arange(2)
print(vmap(f)(y))
```

We probably are going to want to rewrite PyTorch's advanced indexing to get this to work...

**Comment by zou3519** [comment]
Workaround here is to do torch.ones(4)[x[None]][0]

**Comment by zou3519** [comment]
Closing as duplicate of #747

**Comment by mra-h** [comment]
any updates on this?
