### ISSUE TITLE
Forward-mode AD not implemented for logsigmoid activation function

### ISSUE THREAD

**Issue by yhl48** [pytorch/functorch#776]
Hi, I need to use `functorch.jvp` to compute the Jacobian-vector product, but forward-mode AD is not supported for logsigmoid. Following the bug report warning in the doc, I would like to draw your attention to this. Thank you!

**Comment by Chillee** [comment]
Thanks! I'll add some support for it soon.

**Comment by yhl48** [comment]
Is there a good alternative to ``jvp`` for the time being?

**Comment by Chillee** [comment]
Well... you could use PyTorch's `jvp` (https://pytorch.org/docs/stable/generated/torch.autograd.functional.jvp.html), which computes the jvp using 2 vjps.

You could also emulate it yourself using 2 vjps :)

https://github.com/pytorch/functorch/issues/67#issuecomment-875936436

**Comment by Chillee** [comment]
Btw, your specific issue should be fixed by this: https://github.com/pytorch/functorch/pull/778

**Comment by yhl48** [comment]
I believe this has been resolved, closing this now, thanks!
