### ISSUE TITLE
ParameterList causes Segfault in make_functional

### ISSUE THREAD

**Issue by fzimmermann89** [pytorch/functorch#832]
Hi,

the following code
```python
import torch.nn as nn
import torch
import functorch

class test(nn.Module):
    def __init__(self):
        super().__init__()
        self.list = nn.ParameterList(nn.Parameter(torch.ones(1)) for i in range(2))

functorch.make_functional(test())
```
causes
```
terminate called without an active exception
[1]    7559 abort (core dumped)  python
```
without the ParameterList, the code does not fault.

My system:
```
torch version 1.13.0.dev20220524
functorch version 0.3.0a0+76976db
python version 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0]
```

Let me know if you need any additional information or if this is just not supposed to work.

Have a great day,
Felix

**Comment by zou3519** [comment]
Thank you for the issue, @fzimmermann89. Yes, we would expect this to work and the root cause seems to be https://github.com/pytorch/pytorch/issues/78250

**Comment by fzimmermann89** [comment]
This seems to be fixed with current master of functorch and pytorch !
