### ISSUE TITLE
Refactor BatchedTensorImpl

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#86]
[BatchedTensorImpl](https://github.com/facebookresearch/functorch/blob/42a8f6608147fc41debdb3bc9d632dcba1be1a99/functorch/csrc/BatchedTensorImpl.h#L67) got copy-pasted from our previous vmap prototype. It handles multiple batch dimensions at the [same time](https://github.com/facebookresearch/functorch/blob/42a8f6608147fc41debdb3bc9d632dcba1be1a99/functorch/csrc/BatchedTensorImpl.h#L108).

functorch assumes that BatchedTensorImpl only has a single batch dimension. We should change the representation of BatchedTensorImpl to holding a Tensor value, an int64_t bdim, and an int64_t level.

This will:
- improve our codebase
- Make things faster because there is one less layer of indirection

**Comment by vfdev-5** [comment]
I'd like to work on this issue.

**Comment by zou3519** [comment]
Feel free!

**Comment by vfdev-5** [comment]
@zou3519 I sent a PR #239 to fix that, please take a look
