### ISSUE TITLE
Fix handling for `torch.return_types` in PyTorch core

### ISSUE THREAD

**Issue by Chillee** [pytorch/functorch#87]

**Comment by zou3519** [comment]
So we have a couple of options here:
1. Special case torch.return_types.*, just like how we special case namedtuple. torch.return_types are not exactly named tuples: they behave similarly but have some important differences
2. expose torch.return_types.* to Python (they currently don't exist) and register them as pytrees

**Comment by gchanan** [comment]
Is there a good reason we don't expose `torch.return_types` to Python?

**Comment by zou3519** [comment]
@gchanan I don't think so. Looking at the code for torch.return_types (it exists in torch/csrc/autograd/generated/python_torch_functions.cpp), it looks like we didn't take the effort to expose the types by adding them to a module (this would require some more codegen). Comments on the original PR (https://github.com/pytorch/pytorch/pull/15429) imply that we are OK with having torch.return_types be a public API. Maybe @zasdfgbnm or @ezyang remember more about that PR?

**Comment by zasdfgbnm** [comment]
I think there is no reason for not exposing `torch.return_types`.

**Comment by zou3519** [comment]
Fixed by #66614
