### ISSUE TITLE
functionalize() errors on latest CI

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#889]
See https://app.circleci.com/pipelines/github/pytorch/functorch/3173/workflows/46db62fd-2db0-4044-85b2-361ad022577f/jobs/23822 for example failures.

**Comment by ezyang** [comment]
cc @bdhirsh but maybe these are fixed now?

**Comment by bdhirsh** [comment]
My guess is that these are fixed by https://github.com/pytorch/pytorch/pull/81702, but it's kinda hard to tell from that log.

I ran `python test/test_eager_transforms.py TestFunctionalizeCPU` locally though and it looks like it's passing.
