### ISSUE TITLE
AOTAutograd-related test cases failing

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#913]
test/test_memory_efficient_fusion.py
- NoChangeTestCase.test_rand_like
- NoChangeTestCase.test_rand_n

test/test_minifier.py TestMinifier.test_has_mul_minifier

See https://app.circleci.com/pipelines/github/pytorch/functorch/3291/workflows/77fc0ebb-257e-4c5c-94e6-64a32a5c1667/jobs/25312 for details

I'm going to xfail them for now, cc @Chillee @anijain2305

**Comment by Chillee** [comment]
Should be fixed by https://github.com/pytorch/functorch/commit/442483cf1efc0ccaa9b98ec4f51397c4f749c1a7

**Comment by zou3519** [comment]
Thanks, CI looks green now
