### ISSUE TITLE
Can't compile, `asIntArrayRefSlow` doesn't exist

### ISSUE THREAD

**Issue by bwasti** [pytorch/functorch#942]
https://github.com/pytorch/functorch/pull/903 Introduces a bug in compilation: `asIntArrayRefSlow` does not exist.

Here's the issue:
https://github.com/pytorch/functorch/commit/754ee26a1d9e65bd770c6a0917687ae0b0b7a6e3#diff-aa025c5cb4dd033757fb9146e0ed816f5c9072deaa8d907cdca7a635dd33261cR509

Checking out the code 1 commit earlier builds fine.

**Comment by zou3519** [comment]
@bwasti what version of PyTorch are you using?

**Comment by ezyang** [comment]
You need to upgrade your pytorch to a later nightly
