### ISSUE TITLE
Batching rule for searchsorted implementation

### ISSUE THREAD

**Issue by mingu6** [pytorch/functorch#956]
Hi,

Thanks for the great work, really enjoying functorch in my work. I have encountered the following when using vmap on a function which uses torch.searchsorted:

UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::searchsorted.Tensor. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at  /Users/runner/work/functorch/functorch/functorch/csrc/BatchedFallback.cpp:85.)

Looking forward to the implementation.

**Comment by zou3519** [comment]
Thanks for the issue, we can prioritize this. Out of curiosity, what is your use case for functorch?

**Comment by mingu6** [comment]
Hi, thank you to both, much appreciated.

My use case is a research project on deep declarative networks https://arxiv.org/pdf/1909.04866.pdf

We need to implement custom forward/backward passes using implicit differentiation for this class of problems. We implement objective and constraint functions and need to compute VJPs w.r.t. first/second derivatives of these functions over a batch. See (24) for a concrete mathematical representation of my description.

Functorch w/vmap makes for both cleaner code and a meaningful speedup (albeit w/some memory overhead) compared to using torch.autograd.

My particular algorithm relies heavily on searchsorted currently, hence this warning. Hope this answers your question

**Comment by zou3519** [comment]
Thanks for the context. searchsorted is a little more complicated than the one for masked_fill, so it'll take a bit more time, but I should be able to get this to you in the next week

**Comment by mingu6** [comment]
Thanks! Works great on my end, though I haven't benchmarked yet.
