### ISSUE TITLE
Batching rule for masked_fill_

### ISSUE THREAD

**Issue by mingu6** [pytorch/functorch#957]
Hi,

I also ran into this while running my code. Would appreciate implementation to make things faster.

UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::masked_fill.Scalar. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at  /Users/runner/work/functorch/functorch/functorch/csrc/BatchedFallback.cpp:85.)

Thanks.

**Comment by zou3519** [comment]
Thanks for the issue, we can prioritize this

**Comment by zou3519** [comment]
Implemented over at https://github.com/pytorch/functorch/pull/964 . You can use it by building from source (see https://github.com/pytorch/functorch#installing-functorch-from-source) or waiting for the next release

**Comment by mingu6** [comment]
Thanks, works great!
