### ISSUE TITLE
Cuda 11.7 support

### ISSUE THREAD

**Issue by schmidt-jake** [pytorch/functorch#995]
I'm trying to use `functorch.compile.memory_efficient_fusion` inside an [Nvidia-pytorch docker image](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-07.html#rel_22-07) that runs Cuda 11.7. When I try to use `pip install functorch`, I get the following error.

```
RuntimeError: We've detected an installation of PyTorch 1.12 with CUDA 11.7 support.
```

When I try to build from source using:

```bash
BUILD_VERSION=$PYTORCH_BUILD_VERSION pip install git+https://github.com/pytorch/functorch.git
```

I get: `RuntimeError: Error compiling objects for extension` — the stack trace is quite long, but I'd be happy to post it if it would be helpful.

## Versions
```
PyTorch version: 1.13.0a0+08820cb
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: 
GPU 0: A100-SXM-80GB
GPU 1: A100-SXM-80GB

Nvidia driver version: 450.172.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] nvidia-dlprof-pytorch-nvtx==1.8.0
[pip3] torch==1.13.0a0+08820cb
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.14.0a0
[conda] Could not collect
```

**Comment by zou3519** [comment]
Hey @schmidt-jake,

That nvidia-pytorch docker image has pytorch built at 08820cb. We would need to find the corresponding functorch commit that is closest in date to that of the pytorch commit and then build functorch at that point in time from source. (We're working on making this better by just merging functorch into pytorch, but until then...)

Concretely `git show 08820cb` gives me a commit from Thu Jun 23, so I would try functorch at a228a1d (https://github.com/pytorch/functorch/commits/main?after=012d5a28bdbdc56550a41ece8f3df2aeffcd035d+69&branch=main&qualified_name=refs%2Fheads%2Fmain). Could you try `pip install git+https://github.com/pytorch/functorch.git@a228a1d` and see how that goes?

**Comment by schmidt-jake** [comment]
Perfect, thank you for that! I see now it was dumb of me to do `BUILD_VERSION=$PYTORCH_BUILD_VERSION`. I'll try this and report back.

**Comment by schmidt-jake** [comment]
https://github.com/pytorch/functorch.git@a228a1d did the trick!
